version: "3.9"

x-env-vars: &default-env-vars
  MONGODB_CONTAINER_NAME: MongoDB
  DIETS_CONTAINER_NAME: Diets-Service
  MEALS_CONTAINER_NAME: Meals-Service
  NGINX_CONTAINER_NAME: NGINX
  MONGODB_PORT: 27017
  DIETS_PORT: 5002
  MEALS_PORT: 5001
  NGINX_PORT: 80
  MONGO_URI: mongodb://${MONGODB_CONTAINER_NAME}:${MONGODB_PORT}
  DATABASE_NAME: Gal-DB

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: ${MONGODB_CONTAINER_NAME}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - cloud-network

  diets-service:
    build:
      context: .
      dockerfile: ./Diets/Dockerfile
      args:
        DIETS_PORT: ${DIETS_PORT}
    restart: always
    container_name: ${DIETS_CONTAINER_NAME}
    ports:
      - ${DIETS_PORT}:${DIETS_PORT}
    expose:
      - ${DIETS_PORT}
    environment:
      <<: *default-env-vars
    depends_on:
      - mongodb
    volumes:
    - ./Libraries:/Libraries
    networks:
      - cloud-network

  meals-service:
    build:
      context: .
      dockerfile: ./Meals/Dockerfile
      args:
        MEALS_PORT: ${MEALS_PORT}
    restart: always
    container_name: ${MEALS_CONTAINER_NAME}
    ports:
      - ${MEALS_PORT}:${MEALS_PORT}
    expose:
      - ${MEALS_PORT}
    environment:
      <<: *default-env-vars
    depends_on:
      - mongodb
      - diets-service
    volumes:
    - ./Libraries:/Libraries
    networks:
      - cloud-network

  nginx:
    image: nginx:latest
    restart: always
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      <<: *default-env-vars
    depends_on:
      - diets-service
      - meals-service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cloud-network

networks:
  cloud-network: